openapi: 3.0.2
info:
  title: Entity Ref URL API
  version: 1.0.0
paths:
  /entity:
    get:
      summary: Get entity endpoint
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: 'http://localhost:8080/apis/registry/v2/groups/test-group/artifacts/Entity'
